version: '3'

services:

  rabbitmq:
    hostname: rabbitmq
    image: 'rabbitmq:latest'
    command: rabbitmq-server
    ports:
      - '5672:5672'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python api.py
    ports:
      - '5000:80'
    links:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['celery', '-A', 'tasks', 'worker', '-l', 'INFO']
    links:
      - rabbitmq

  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    command: python ftp.py
    ports:
      - '21:21'